version: "3.5"

services:
  sim:
    image: tc-netem-cl
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == worker2
    networks:
      - my_network
    hostname: sim
    stdin_open: true
    tty: true
    volumes:
      - $LOG_PATH_SHAPER:/logs/
    env_file: 
      - shaper.env
    cap_add: 
      - NET_ADMIN
    expose:
      - "57832"

  tcpdump_leftnet:
    image: kaazing/tcpdump
    container_name: vegvisir_tcpdump_leftnet
    stdin_open: true
    tty: true
    depends_on:
      - sim
    cap_add:
      - NET_ADMIN
    volumes:
      - $LOG_PATH_SHAPER:/logs/
    network_mode: "container:sim"
    command: ["-v", "--interface", "eth0", "--packet-buffered", "-w", "/logs/tcpdump_leftnet.pcap" ]

  tcpdump_rightnet:
    image: kaazing/tcpdump
    container_name: vegvisir_tcpdump_rightnet
    stdin_open: true
    tty: true
    depends_on:
      - sim
    cap_add:
      - NET_ADMIN
    volumes:
      - $LOG_PATH_SHAPER:/logs/
    network_mode: "container:sim"
    command: ["-v", "--interface", "eth1", "--packet-buffered", "-w", "/logs/tcpdump_rightnet.pcap" ]

  server:
    server:
    image: martenseemann/quic-go-interop:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == worker1
    networks:
      - my_network
    hostname: server
    stdin_open: true
    tty: true
    volumes:
      - $WWW:/www:ro
      - $CERTS:/certs:ro
      - $LOG_PATH_SERVER:/logs/
    env_file: 
      - server.env
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    ulimits:
      memlock: 67108864

  client:
    image: godashcl
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == worker2
    networks:
      - my_network
    hostname: client
    stdin_open: true
    tty: true
    volumes:
      - $DOWNLOAD_PATH_CLIENT:/downloads:delegated
      - $CERTS:/certs:ro
      - $LOG_PATH_CLIENT:/logs/
    env_file: 
      client.env
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    ulimits:
      memlock: 67108864

networks:
  leftnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
    enable_ipv6: true
    ipam:
      config:
        - subnet: 193.167.0.0/24
        - subnet: fd00:cafe:cafe:0::/64
  rightnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
    enable_ipv6: true
    ipam:
      config:
        - subnet: 193.167.100.0/24
        - subnet: fd00:cafe:cafe:100::/64