# version: "3.5"

# services:
#   client:
#     image: alpine
#     container_name: alpine1
#     networks:
#       - test-net
  

#   server:
#     image: alpine
#     container_name: alpine2
#     networks:
#       - test-net

# networks:
#   test-net:

#     external: true



version: '3.8'

services:
  sim:
    image: $SHAPER
    hostname: sim
    stdin_open: true
    tty: true
    volumes:
      - $LOG_PATH_SHAPER:/logs/
    env_file: 
      - shaper.env
    cap_add: 
      - NET_ADMIN
    expose:
      - "57832"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == worker1
    networks:
      - my_network

  client:
    image: $CLIENT
    hostname: client
    stdin_open: true
    tty: true
    volumes:
      - $DOWNLOAD_PATH_CLIENT:/downloads:delegated
      - $CERTS:/certs:ro
      - $LOG_PATH_CLIENT:/logs/
    env_file: 
      client.env
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    ulimits:
      memlock: 67108864
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == worker1
    networks:
      - my_network

  tcpdump_leftnet:
    image: kaazing/tcpdump
    container_name: vegvisir_tcpdump_leftnet
    stdin_open: true
    tty: true
    depends_on:
      - sim
    cap_add:
      - NET_ADMIN
    volumes:
      - $LOG_PATH_SHAPER:/logs/
    network_mode: "container:sim"
    command: ["-v", "--interface", "eth0", "--packet-buffered", "-w", "/logs/tcpdump_leftnet.pcap" ]

  tcpdump_rightnet:
    image: kaazing/tcpdump
    container_name: vegvisir_tcpdump_rightnet
    stdin_open: true
    tty: true
    depends_on:
      - sim
    cap_add:
      - NET_ADMIN
    volumes:
      - $LOG_PATH_SHAPER:/logs/
    network_mode: "container:sim"
    command: ["-v", "--interface", "eth1", "--packet-buffered", "-w", "/logs/tcpdump_rightnet.pcap" ]

  server:
    image: $SERVER
    hostname: server
    stdin_open: true
    tty: true
    volumes:
      - $WWW:/www:ro
      - $CERTS:/certs:ro
      - $LOG_PATH_SERVER:/logs/
    env_file: 
      - server.env
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    ulimits:
      memlock: 67108864
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.type == worker2
    networks:
      - my_network

networks:
  my_network:
    driver: overlay


